services:
  - type: web
    name: keto-hotel
    env: docker
    plan: free
    region: oregon
    branch: main
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: local
      - key: APP_KEY
        sync: true
      - key: DB_HOST
        value: http://sql12.freesqldatabase.com/
      - key: DB_DATABASE
        value: sql12773405
      - key: DB_USERNAME
        value: sql12773405
      - key: DB_PASSWORD
        value: cTbjiggxZR
