services:
  - type: web
    name: hotel-management-laravel
    env: docker
    plan: free
    branch: main
    buildCommand: ""
    startCommand: "php artisan serve --host=0.0.0.0 --port=10000"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false
      - key: DB_HOST
        value: localhost
      - key: DB_DATABASE
        value: hotel
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: 
